# Generated by Django 6.0 on 2025-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0007_task_assignee_email_taskinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinvite',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
